StephanJoubert/home_assistant_solarman

custom_components/solarman/translations/pl.json
Hi,
I added Polish translation 🙂
=> Polish translation

custom_components/solarman/translations/pt-BR.json
Please, Add Brazilian Portuguese Translation
=> Add Brazilian Portuguese Translation

custom_components/solarman/inverter_definitions/solis_hybrid.yaml
* Optimise Modbus requests
* Fix Daily Generation state_class (Fixes #44)
* Fix Monthly Generation register typo (Fixes #56)
=> solis_hybrid.yaml: Multiple fixes

custom_components/solarman/inverter_definitions/solis_hybrid.yaml
=> Changing state_class to total_increasing

custom_components/solarman/inverter_definitions/sofar_g3hyd.yaml, custom_components/solarman/sensor.py
=> Updated sofar solar hyd and g3 based on actual data

custom_components/solarman/inverter_definitions/deye_string.yaml
=> Set UOM of  "Output Active Power" from kWh to W

custom_components/solarman/inverter_definitions/solis_hybrid.yaml
Added 'charge from grid' status for Solis Hybrid integration
=> Added 'charge from grid' status for Solis Hybrid Inverters

custom_components/solarman/solarman.py
I've made some modifications that perform additional checks on the embedded modbus packet so that invalid responses can be rejected.  These checks are similar to those performed by the pysolarmanv5 library, but I don't really have the time to integrate that entire library currently.
This should fix [issue 120](https://github.com/StephanJoubert/home_assistant_solarman/issues/120).  Additionally, [issue 122](https://github.com/StephanJoubert/home_assistant_solarman/issues/122) also seems to have very similar symptoms.
I have been running this fix successfully for nearly two weeks now.  I no longer see any bad values within my logged data.
=> Modified to add additional checks on received V5 packet & embedded modbus frame

README.md, custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/deye_sg04lp3.yaml
See #88
* Add parameter file for DEYE SUN-12K-SG04LP3-EU, tested with data logger LSW3_15_FFFF_1.0.84. Based on the work by wendtc, ondrejbartas and pv-joy.a
* Trying to collapse number of requests to increase reliability (may be collapsed further)
=> GH-88 Add DEYE SUN-12K-SG04LP3-EU

custom_components/solarman/inverter_definitions/sofar_hyd3k-6k-es.yaml
Adding inverter definition for HYD3000/4000/5000/6000-ES with complete alert definition.
=> Adding inverter definition for HYD3000/4000/5000/6000-ES

custom_components/solarman/inverter_definitions/deye_string.yaml
change kWh to W as this works for my DEYE SUN600
=> Update deye_string.yaml - Change kWh to W

README.md, custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/zcs_azzurro-ktl-v3.yaml
Despite being very close to LSW-3 definition, some registers differ.
P.S. README.MD formatting was done automatically, pls treat it with understanding.
=> Adding inverter definition for ZCS Azzurro 3.3/4.4/5.5/6.6 KTL-V3

custom_components/solarman/inverter_definitions/deye_4mppt.yaml, custom_components/solarman/inverter_definitions/deye_string.yaml
While working on #195 I noticed that this entry might've been copy&pasted badly.
=> Change output frequency class to actually be frequency

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/deye_2mppt.yaml
I modified the configuration for SUN2000G3 to match the SUN600G3. 
It will probably also work for the 800G3, but i don't have a device to test. 
will resolve #222
=> added configuration for Deye SUN600G3

custom_components/solarman/translations/it.json
Creating a separate Pull Request just for the Italian Translation as suggested by @YodaDaCoda
=> Italian Transaltion

custom_components/solarman/inverter_definitions/deye_4mppt.yaml, custom_components/solarman/inverter_definitions/deye_string.yaml, custom_components/solarman/inverter_definitions/sofar_hyd3k-6k-es.yaml
=> Ouput -> Output typo fix

custom_components/solarman/inverter_definitions/deye_hybrid.yaml
Added Daily Battery Charge and Discharge.
Working on my Deye 5KVA
=> Added Daily Battery Charge and Discharge to deye_hybrid.yaml

custom_components/solarman/solarman.py
New validation added to prevent race condition: 
- generation of a sequence number
- sending sequence number in the echo field or requests 
- validating that the expected sequence number is found in responses before parsing the data 
Any mismatched responses are ignored. They are likely old responses received too late and the application state cannot deal with them.
Additional validation added:
- ensure that the response is of the expected length before parsing
=> fix: Fixed validation. Use a sequence number. Issue #268

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/hyd-zss-hp-3k-6k.yaml, hacs.json
I added support for my zcs azzurro 27**** hybrid inverter
=> hyd-zss-hp-3k-6k 27****** sn added

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/solis_s6-gr1p.yaml
=> Add yaml for S6 Series 

custom_components/solarman/inverter_definitions/solis_hybrid.yaml
* Added: 33141 -> BMS Battery Voltage
* 33142 -> BMS Battery Current
* 33143 -> BMS Battery Charge Current Limit
* 33144 -> BMS Battery Discharge Current Limit
* 33157 -> Inverting/Rectifing Power
* Fix trailing whitespace
* Fix state_class, isstr for lookup registers
=> Solis Hybrid Updates

custom_components/solarman/inverter_definitions/deye_2mppt.yaml, custom_components/solarman/inverter_definitions/deye_4mppt.yaml, custom_components/solarman/services.yaml
Fix bug for Deye 4MPPT
https://github.com/StephanJoubert/home_assistant_solarman/issues/367 https://github.com/StephanJoubert/home_assistant_solarman/issues/391 https://github.com/StephanJoubert/home_assistant_solarman/issues/388
=> Update deye_4mppt.yaml // deye_2mppt.yaml

custom_components/solarman/inverter_definitions/solis_hybrid.yaml
Changes to solis_hybrid inverter definitions:
- Added Timed Charge and Timed Discharge sensors
- Fixed link to Modbus Pdf in comments
=> Added Timed Charge/Discharge sensors in Solis Hybrid definition

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/Afore_BNTxxxKTL-2mppt.yaml
Add comment how to enable pymodbus in AFORE inverter,
add afore definition in const.py
=> More fixes for AFORE

custom_components/solarman/const.py
Path adds auto scan of inverter_definitions directory to get all files in it
=> No hardcoded yaml names

custom_components/solarman/const.py
Fixes: {"message":"Invalid handler specified"}
=> Update const.py, Fixes #423

custom_components/solarman/inverter_definitions/deye_sg04lp3.yaml
several additional counters added in line with open requests from issue #88 and some additional parameters not yet requested in the issue.
=> Additions to deye_sg04lp3.yaml
