custom_components/solarman/sensor.py
Adding the "unique_id" to each sensor entity allows a user to do things such as:
- rename the entity
- change the icon
- apply it to an "area"
- disable/enable entity
According to Home Assistant documentation, the unique_id must be a unique identifier that cannot be changed.  e.g. a serial number is good, an ip address is bad.
I've added a unique_id by passing the serial number into the Sensor entity.  Perhaps it's better to expose the serial number from the Inverter class instead?
=> Add unique_id to sensor entities

custom_components/solarman/parameters.yaml, custom_components/solarman/sensor.py
This fixes sensors that should show up as text values but currently show up in HA as a number graph.
Please give it some testing before merging to check I got all the relevant sensors in the parameters.yaml.
Note:  The following steps are needed to fix an existing integration (I don't know for sure, but it's possible it might fix itself after a few hours/days)
1. Comment out the solarman block of settings in configuration.yaml
2. restart HASS
3. On the overview or custom dashboard, the sensors will be showing a warning.  Open each of the text sensors (only the text sensors) and remove the entities - this will delete the history.
4. Uncomment the solarman block of settings
5. restart HASS
The text sensors will have been recreated and will show the correct status history in the UI.
=> Fix for text value sensors showing up as number graphs

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/sofar_g3hyd.yaml
- tested on firmware LSW3_15_270A_1.32
=> Support for  Sofar G3 also HYD 5-20KTL-3PH

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/sofar_wifikit.yaml
Adds a new inverter definition to support inverters with the "wifikit"
embedded data logger, with serial numbers starting `804xxxxxx` and
potentially others.
NOTE: Generation Power on the ME3000-SP returns a "special" 
value, 65534 when no generation is occurring. This is problematic
because it means generation power statistics will be inaccurate
overnight unless this value is rejected.
I have another small code change which I can add another PR for which
allows to set a range of valid values and returns a default value if a field
is outside that range - this PR does _not_ contain the relevant changes
here but I haven't heard anything on the issue for that (#83).
Signed-off-by: Ben Agricola <ben+git@agrico.la>
=> Add Sofarsolar Wifikit inverter definition

custom_components/solarman/inverter_definitions/deye_string.yaml, custom_components/solarman/parser.py, custom_components/solarman/solarman.py, customization.md
This fixes https://github.com/StephanJoubert/home_assistant_solarman/issues/111
This introduce "invalid" option to parser, so that the complete dataset could be ignored,
when e.g. "Total Production" is zero during startup of the inverter.
=> Fix zero values on total production lead to wrong error counting

custom_components/solarman/const.py
Will resolve the issue below
Logger: homeassistant.components.sensor
Source: custom_components/solarman/solarman.py:34
Integration: Sensor (documentation, issues)
First occurred: 19:54:15 (1 occurrences)
Last logged: 19:54:15
Error while setting up solarman platform for sensor Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/solarman/sensor.py", line 79, in async_setup_entry
_do_setup_platform(hass, entry.options, async_add_entities)
File "/config/custom_components/solarman/sensor.py", line 51, in _do_setup_platform
inverter = Inverter(path, inverter_sn, inverter_host, inverter_port, inverter_mb_slaveid, lookup_file)
File …
=> Fix missing underscore

custom_components/solarman/sensor.py, custom_components/solarman/solarman.py
When working on #171 I've noticed that the data logger stick (being in cloud mode) is often times busy, which resulted in requests to fail more often then not. Extending the retry mechanism as shown in this PR has alleviated the problem for my system.
* increase number of retry attempts to increase chance of getting data back from a busy data logger stick
* try to re-open socket if lost on request attempt
* decrease timeout slightly (non-busy stick takes <1sec)
=> Extended retry mechanism

custom_components/solarman/solarman.py
Previously the logger published the exception as an general error. Now it uses the logger defined in line 10. With this added in the `configuration.yaml`:
```
logger:
default: error
logs:
custom_components.solarman: fatal
```
the error isn't showing anymore. Solves #175
=> Use logger for this domain

custom_components/solarman/inverter_definitions/sofar_lsw3.yaml
See https://github.com/StephanJoubert/home_assistant_solarman/issues/187
* I don't see the register range `0x0105` to `0x0114` used in the file for any actual data point
* As per https://github.com/StephanJoubert/home_assistant_solarman/issues/187 it seems that querying for it, breaks data fetching since https://github.com/StephanJoubert/home_assistant_solarman/pull/125 (rightfully, given the packet validation does the right thing here...)
=> LSW3: remove unused register range

custom_components/solarman/solarman.py
See https://github.com/StephanJoubert/home_assistant_solarman/issues/187
* only close socket if it was ever opened successfully
* this is only the bug-fix of #194 without the partial roll-back, as it seems we do not them it
Fixing stack traces a la as reported by @heebo1974 
```
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/solarman/solarman.py", line 175, in update
self.get_statistics()
File "/config/custom_components/solarman/solarman.py", line 234, in get_statistics
sock.close()
UnboundLocalError: local variable 'sock' referenced before assignment
```
=> bugfix: retry mechanism

custom_components/solarman/solarman.py
If `connect_to_server()` excepts, `sock` never gets assigned a value, and in fact never gets defined, resulting in a exception that `sock` is referenced before assignment when trying to `sock.close()`.
=> fix: don't error if socket doesn't connect

custom_components/solarman/sensor.py, custom_components/solarman/solarman.py
Provides Home Assistant the information it needs to group the Sensors into a single Device, providing a nicer user experience for viewing information about the inverter's stats.
Integrations view:
Device view:
=> Group Sensors into a Device

custom_components/solarman/inverter_definitions/sofar_g3hyd.yaml
I have reviewed the registry values from the file that ZCS shared and have removed comments from sensors that were removed.
I've added translations for Italian language and edited the documentation to better identify rebranded 3-phase Sofar inverters.
This is the file ZCS shared: [ModBus-RTU.Communication.Protocol.3PH.Hybrid.and.Inverter.pdf](https://github.com/StephanJoubert/home_assistant_solarman/files/10862339/ModBus-RTU.Communication.Protocol.3PH.Hybrid.and.Inverter.pdf)
=> Added missing parameters from ZCS AZZURRO 3PH inverters

README.md, custom_components/solarman/inverter_definitions/deye_2mppt.yaml
This PR updates the definition file that is used for various deye microinverters
Here are the changes:
- Add radiator temperature to the list of parameters
- Fix running status parameter mapping
- Remove `invalidate_all` from validation as it causes the integration to not work at all in freshly deployed setups
- Add the definition yaml to the readme
- General auto-formatting by pycharm
=> Update definition for Deye 2 MPPT

.gitignore, README.md
As you, @YodaDaCoda, have suggested for the italian translation, I am similarly making a separate pull request for a slight correction on the Readme.MD. 
This, under the "Lookup Files" section does not explain which file to use for 1-Phase or 3-Phase inverters, and this can lead to the usage of the incorrect definition. I have added a note stating which one is for single-phase and which one is for three-phase.
=> Clarification on ZCS AZZURRO 3PH Inverters

custom_components/solarman/inverter_definitions/deye_2mppt.yaml, custom_components/solarman/parser.py
Compared to the stock solarman app the deye_2mppt.yaml file lacked a lot of information.
I added a lot additional information after looking up the register contents and compared them to the values shown in solarman app. 
Additional Information:
- Daily Production 1
- Daily Production 2
- Total Production 1
- Total Production 2
- Active Power Regulations
- Grid Current
- Grid Voltage Upp Limit
- Grid Voltage Lower Limit
- Grid Frequency Upper Limit
- Grid Frequency Lower Limit
- Overfrequency And Load Reduction Starting Point
- Overfrequency And Load Reduction Percentage
- ON-OFF Enable
- Island Protection Enable
- Overfrequency&Load-shedding Enable
- Hardware Version
- DC Master Firmware Version
- AC Version Number
- Rated Power
- Communication Protocol Version
- Start-up Self-checking …
=> Add additional entities for Deye_2mppt

custom_components/solarman/const.py, custom_components/solarman/inverter_definitions/solis_3p-4g.yaml
Configuration for Solis-3P(5-10)K-4G series inverters.
Registers address and description are taken from [official documentation](https://ginlongsolis.freshdesk.com/support/solutions/articles/36000340158-modbus-communication-for-solis-inverters)
Tested on my own setup with DLS-W logger.
Data checked with Solis Cloud platform. In consistance.
=> Solis 4G Three Phase Inverter definition

custom_components/solarman/inverter_definitions/sofar_hyd3k-6k-es.yaml
A bunch of typos and wrong case fixes, especially on the unit of measurment (the correct way is `kWh` for example) to better work with the Energy panel.
=> Fix typos and unit of measurements/entity case for hyd3k-6k

custom_components/solarman/inverter_definitions/deye_hybrid.yaml, custom_components/solarman/parser.py
- Update deye_hybrid.yaml to use mask for time of use enable registers
I have a DEYE 8kW inverter and for some of the registers where a 0 or 1 is expected, mine does not return a 0 or a 1, resulting in a LOOKUP string as the state of the enity. I saw however that bit 0 in those registers is the bit of interest. This PR adds a mask to the unsigned rules (1 & 3) so you can mask the required bit or bits. A possible further improvement can be adding a shift, so you can mask a bit or bits in the middle of the register value and shift it down (this has not been added in this PR)
=> Add mask to rule 1 and rule 3

custom_components/solarman/inverter_definitions/deye_hybrid.yaml, custom_components/solarman/parser.py, customization.md
Add following to deye_hybrid.yaml:
- Grid Current L1
- Grid Current L2
- Grid Frequency
- Time of Use Time [1 - 6]
- Time of Use Power [1 - 6]
- Time of Use SOC [1 - 6]
- Time of Use Enabled [1 - 6] 
Update customization.md with new rule as well as missing rules
This allows using the Sunsynk dashboard (https://github.com/slipx06/Sunsynk-Home-Assistant-Dash) as well as the Sunsynk Power Flow Card (https://github.com/slipx06/sunsynk-power-flow-card):
=> Add new rule for parsing time values.

custom_components/solarman/inverter_definitions/hyd-zss-hp-3k-6k.yaml
Actually the hyd-zss-hp-3k-6k inverter definition has marked all "Today" totalizer with
```yaml
state_class: 'total'
```
This cause a big diff on 1st measure of each day.
According to docs and other inverter definition this sensor need to be.
``` yaml
state_class: 'total_increasing'
```
Resubmitting #352 because has been canceled due earlier repo cancellation.
=> Fix Today totalizer for hyd-zss-hp-3k-6k inverter #352

custom_components/solarman/sensor.py, custom_components/solarman/solarman.py
With the current implementation, as soon as the sun goes down, we get these invalid states in the home assistant history:
This is annoying and might also mess with the long-term statistics.
Therefore, this PR fixes that by clearing the cache when the inverter enters the `Disconnected` state.
With this change, the graph now correctly shows no data for the time where there was no connection to the inverter:
=> Invalidate any cached previous readings when disconnected

custom_components/solarman/parser.py
Pass through unknown lookup table values, rather than lose it through meaningless `LOOKUP` value
=> Passthrough missing lookup table value

custom_components/solarman/inverter_definitions/kstar_hybrid.yaml
The new 1.5 version of the integration uses the pysolarman library which is stricter with the protocol. In this case, we were requesting more than 125 registers at a time, so it failed on the new update. So we need to restructure the requests to only request a max of 125 registers.
=> KSTAR: Reorganise registers into blocks of 125

custom_components/solarman/inverter_definitions/deye_sg04lp3.yaml
remove invalidate_all from battery temp for deye_sg04lp3.yaml definition as inverters in parallel read -100 degrees celsius for connected batteries on the slaves (master battery-temp is correct though)
=> remove invalidate_all from battery temp for deye_sg04lp3.yaml

custom_components/solarman/inverter_definitions/solis_hybrid.yaml
Adds two holding registers to the Solis hybrid definition. Also requires definition of the register range for holding registers to be expanded to include them (lower limit reduced to 43000)
=> Add Backup SOC and Overdischarge SOC

custom_components/solarman/inverter_definitions/solis_3p-4g.yaml
In recent version os solarman, sending request to 4999 register doesn't work. Custom integration doesn't load in HA with this inverter definition.
As long as  the register 4999 value is not very usefull, let just remove it and get back to work inverter definition.
=> remove 4999 register request

custom_components/solarman/solarman.py
This change allows to see the Modbus addresses in hex format too in the logs, so you can more easily spot errors in the inverter YAML definition file (which normally uses register addresses in hex format).
The log entries will change from this:
```text
2024-01-21 13:31:31.174 WARNING (SyncWorker_1) [custom_components.solarman.solarman] Querying [1028-1051] failed with exception [Empty: ]
```
To this:
```text
2024-01-21 13:31:31.174 WARNING (SyncWorker_1) [custom_components.solarman.solarman] Querying [1028-1051 (0x0404-0x041B)] failed with exception [Empty: ]
```
=> Show HEX Modbus addresses too in the logs

custom_components/solarman/parser.py, customization.md
Deals with YAML inverter definition files that are missing the `scale` parameter-item and cause an exception.
=> Automatically set scale to 1 when undefined in YAML

README.md, custom_components/solarman/sensor.py
Moves the status entities `Status_connection` and `Status_lastUpdate` to the Diagnostic category in Home Assistant, so that they don't appear on the main dashboard automatically.
=> Move status entities to Diagnostic category

custom_components/solarman/inverter_definitions/solis_hybrid.yaml, custom_components/solarman/parser.py, customization.md
Read multiple registers and pass them through as array without
processing. Useful when you need to read multiple registers atomically.
For my usecase, I wanted to extract the inverter date time as a single
register to parse later using a jinja2 template.
=> Add new raw parser
